export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CONTACT_USER ="CONTACT_USER"
export const SEARCH_RESULT = "SEARCH_RESULT"